---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unleash
  namespace: default
spec:
  chart:
    spec:
      chart: unleash
      sourceRef:
        kind: HelmRepository
        name: unleash
      version: 2.8.0
  interval: 1m0s
  values:
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      hosts:
      - host: unleash.testaviva.internal
        paths:
          - path: /
            pathType: prefix
      tls: 
        - secretName: unleash-testaviva-internal-tls
          hosts:
            - unleash.testaviva.internal
