---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unleash
  namespace: default
spec:
  chart:
    spec:
      chart: unleash
      sourceRef:
        kind: HelmRepository
        name: unleash
      version: 2.8.0
  interval: 1m0s
  values:
    ingress:
      enabled: true
      hosts:
      - host: unleash.testaviva.local
        paths:
          - path: /
            pathType: Prefix
